# -*- coding: utf-8 -*-
"""
STAR alignment module deploy — the analysis stage that runs AFTER the SRA download on the cluster.

When the analysis module is "bulk_rna_seq" and the cluster is on, this fills the vendored
star_template/ config.sh from the form + the download run, ships it to <download_root>/star, and
AUTO-CHAINS it: a launcher job (star_launch.sh) waits for the download's PIPELINE_COMPLETE.txt
(LSF `-w ended(<download watchdog>)` + a sentinel poll), then runs ./run_star_pipeline.sh, which
reads the downloaded *.fastq.gz, resolves/builds a STAR genome index by organism, and aligns.

Reuses cluster_deploy's fill_config / SSH transport / diagnose_failure (the download path is
unchanged). STAR consumes FASTQ, never .sra.
"""
import os
import csv
import json
import shutil
from collections import Counter

from progress import NULL
import cluster_deploy

HERE = os.path.dirname(os.path.abspath(__file__))
STAR_TEMPLATE_DIR = os.path.join(HERE, "star_template")
REGISTRY_FILE = os.path.join(HERE, "star_index_registry.json")

# config.sh vars we fill (name -> default). Numerics are written unquoted.
STAR_CONFIG_DEFAULTS = {
    "FASTQ_INPUT_DIR": "/data/CHANGE_ME/fastqs",
    "BAM_OUT": "/data/CHANGE_ME/STAR_bams",
    "GENOME_DIR": "",
    "SJDB_GTF": "",
    "SJDB_OVERHANG": 100,
    "RUNTABLE": "",
    "SCRATCH": "/scratch/$USER",
    "THREADS": 6,
    "SORT_RAM": 20000000000,
    "STAR_EXTRA_ARGS": "",
    "MEM_MB": 64000,
    "MEM_RUSAGE": 10000,
    "WALL": "24:00",
    "LSF_QUEUE": "",
    "JOB_TAG": "star",
    "WATCHDOG_INTERVAL_MIN": 30,
    "MAX_STALL_PASSES": 2,
    "STAR_MODULE": "STAR/2.7.10b",
    "SAMTOOLS_MODULE": "samtools",
    "ORGANISM": "Homo sapiens",
    "STAR_INDEX_ROOT": "",
    "REF_FASTA_URL": "",
    "REF_GTF_URL": "",
    "BUILD_THREADS": 16,
    "BUILD_MEM_MB": 64000,
    "BUILD_MEM_RUSAGE": 4000,
    "BUILD_WALL": "8:00",
}
STAR_NUMERIC = {"SJDB_OVERHANG", "THREADS", "SORT_RAM", "MEM_MB", "MEM_RUSAGE",
                "WATCHDOG_INTERVAL_MIN", "MAX_STALL_PASSES",
                "BUILD_THREADS", "BUILD_MEM_MB", "BUILD_MEM_RUSAGE"}


def _resolve_star_cfg(star_cfg):
    vals = dict(STAR_CONFIG_DEFAULTS)
    for k in STAR_CONFIG_DEFAULTS:
        if star_cfg and k in star_cfg and str(star_cfg[k]).strip() != "":
            vals[k] = star_cfg[k]
    return vals


def _find_runtable(P, slug):
    for cand in (P.runtable_filtered_csv(slug), P.runtable_filtered_csv(slug).replace(".csv", "_v2.csv")):
        if os.path.exists(cand):
            return cand
    return None


def detect_organism(P, sel, override=None):
    """Dominant Organism for the selected line's runs (the reconstructed run table has an Organism
    column); explicit override wins; default 'Homo sapiens' (the default query is human)."""
    if override and str(override).strip():
        return str(override).strip()
    slug = cluster_deploy._slug((sel or {}).get("canonical", ""))
    for cand in (_find_runtable(P, slug), P.runtable_all_csv):
        if cand and os.path.exists(cand):
            try:
                rows = list(csv.DictReader(open(cand, encoding="utf-8")))
                c = Counter((r.get("Organism") or "").strip() for r in rows if (r.get("Organism") or "").strip())
                if c:
                    return c.most_common(1)[0][0]
            except Exception:
                pass
    return "Homo sapiens"


def _url_registry_for(organism):
    try:
        data = json.load(open(REGISTRY_FILE, encoding="utf-8")).get("reference_urls", {})
        key = " ".join((organism or "").lower().split())
        norm = {" ".join(k.lower().split()): v for k, v in data.items()}
        return norm.get(key, {})
    except Exception:
        return {}


def _star_launch_sh(download_root):
    """Sentinel launcher: wait for the download to finish, then exec the STAR pipeline."""
    dl = download_root.rstrip("/")
    return (
        "#!/usr/bin/env bash\n"
        "# star_launch.sh -- generated by SpliceScout. Wait for the SRA download to finish, then launch\n"
        "# STAR. Submitted with bsub -w ended(<download watchdog>) when known; this poll covers the case\n"
        "# where the watchdog id is unknown or already gone.\n"
        'HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"\n'
        f"DL_ROOT='{dl}'\n"
        "IVL=60\n"
        "MAXW=1440\n"
        "i=0\n"
        'while [ "$i" -lt "$MAXW" ]; do\n'
        '  [ -f "$DL_ROOT/PIPELINE_COMPLETE.txt" ] && break\n'
        '  [ -f "$DL_ROOT/PIPELINE_STALLED.txt" ] && break\n'
        '  i=$((i+1)); sleep "$IVL"\n'
        "done\n"
        'echo "[star_launch] download finished (or wait elapsed) -> launching STAR pipeline"\n'
        'exec bash "$HERE/run_star_pipeline.sh"\n'
    )


def _write_star_instructions(P, vals, download_root):
    txt = (
        "STAR alignment bundle (Bulk RNA-seq module)\n"
        "===========================================\n"
        f"Reads FASTQs from : {vals['FASTQ_INPUT_DIR']}\n"
        f"Writes BAMs to    : {vals['BAM_OUT']}\n"
        f"Organism          : {vals['ORGANISM']}\n"
        f"Genome index      : {vals.get('GENOME_DIR') or '(resolve by organism / build-once)'}\n\n"
        "Autonomous mode launches this automatically AFTER the download finishes. To run it manually:\n"
        f"  cd {download_root.rstrip('/')}/star\n"
        "  chmod +x *.sh\n"
        "  ./run_star_pipeline.sh\n"
        "Watch:  bash status.sh   (or tail -f <BAM_OUT>/watchdog.log)\n"
        "Done when <BAM_OUT>/PIPELINE_COMPLETE.txt appears.\n"
    )
    with open(os.path.join(P.star_dir, "RUN_STAR_ON_CLUSTER.txt"), "w", encoding="utf-8", newline="\n") as f:
        f.write(txt)


def build_star_bundle(P, sel, download_root, star_cfg, download_job_tag="sra", reporter=NULL):
    """Assemble runtable/star/ (filled config.sh + vendored scripts + registry + runtable + launcher),
    zip it, and return a summary. Returns None if the template is missing."""
    if not os.path.isdir(STAR_TEMPLATE_DIR):
        print(f"  STAR BUNDLE: vendored template missing at {STAR_TEMPLATE_DIR} -> skipping")
        return None
    reporter.set_detail("assembling STAR bundle…")
    if os.path.isdir(P.star_dir):
        shutil.rmtree(P.star_dir, ignore_errors=True)
    os.makedirs(P.star_dir, exist_ok=True)

    # vendored scripts (LF), everything except config.sh (generated)
    for name in sorted(os.listdir(STAR_TEMPLATE_DIR)):
        srcf = os.path.join(STAR_TEMPLATE_DIR, name)
        if os.path.isfile(srcf) and name != "config.sh":
            txt = open(srcf, encoding="utf-8", errors="replace").read().replace("\r\n", "\n").replace("\r", "\n")
            with open(os.path.join(P.star_dir, name), "w", encoding="utf-8", newline="\n") as f:
                f.write(txt)
    # ship the registry (organisms-block lookup happens on the cluster)
    if os.path.exists(REGISTRY_FILE):
        txt = open(REGISTRY_FILE, encoding="utf-8").read().replace("\r\n", "\n").replace("\r", "\n")
        with open(os.path.join(P.star_dir, "star_index_registry.json"), "w", encoding="utf-8", newline="\n") as f:
            f.write(txt)

    slug = cluster_deploy._slug((sel or {}).get("canonical", "") if sel else "")
    organism = detect_organism(P, sel, (star_cfg or {}).get("ORGANISM"))
    urls = _url_registry_for(organism)
    dl = download_root.rstrip("/")
    star_root = f"{dl}/star"

    vals = _resolve_star_cfg(star_cfg)
    vals["FASTQ_INPUT_DIR"] = f"{dl}/by_study"
    vals["BAM_OUT"] = f"{dl}/STAR_bams"
    vals["JOB_TAG"] = f"{(download_job_tag or 'sra')}_star"
    vals["ORGANISM"] = organism
    if urls.get("fasta_url") and not str(vals.get("REF_FASTA_URL", "")).strip():
        vals["REF_FASTA_URL"] = urls["fasta_url"]
    if urls.get("gtf_url") and not str(vals.get("REF_GTF_URL", "")).strip():
        vals["REF_GTF_URL"] = urls["gtf_url"]
    if urls.get("sjdb_overhang") and not (star_cfg or {}).get("SJDB_OVERHANG"):
        vals["SJDB_OVERHANG"] = urls["sjdb_overhang"]

    # copy the deep-dive run table (Run/BioSample/Organism) so STAR merges runs per BioSample
    src_rt = _find_runtable(P, slug)
    if src_rt:
        shutil.copyfile(src_rt, os.path.join(P.star_dir, f"SraRunTable_{slug}.csv"))
        vals["RUNTABLE"] = f"{star_root}/SraRunTable_{slug}.csv"
    else:
        vals["RUNTABLE"] = ""
        print("  STAR BUNDLE: no filtered run table found -> RUNTABLE empty (one BAM per run)")

    template = open(os.path.join(STAR_TEMPLATE_DIR, "config.sh"), encoding="utf-8").read()
    with open(os.path.join(P.star_dir, "config.sh"), "w", encoding="utf-8", newline="\n") as f:
        f.write(cluster_deploy.fill_config(template, vals, numeric=STAR_NUMERIC, defaults=STAR_CONFIG_DEFAULTS))
    with open(os.path.join(P.star_dir, "star_launch.sh"), "w", encoding="utf-8", newline="\n") as f:
        f.write(_star_launch_sh(download_root))

    _write_star_instructions(P, vals, download_root)
    cluster_deploy._zip_dir(P.star_dir, P.star_bundle_zip)
    print(f"  STAR BUNDLE: organism={organism!r} index={vals.get('GENOME_DIR') or '(resolve/build)'} "
          f"-> {os.path.basename(P.star_bundle_zip)}")
    reporter.set_detail(f"STAR bundle ready (organism {organism})")
    return {"fastq_input": vals["FASTQ_INPUT_DIR"], "bam_out": vals["BAM_OUT"], "job_tag": vals["JOB_TAG"],
            "organism": organism, "runtable": vals["RUNTABLE"], "genome_dir": vals.get("GENOME_DIR", ""),
            "star_root": star_root}


def submit_star_over_ssh(P, cluster_cfg, secrets, download_root, reporter=NULL):
    """Upload the STAR bundle and submit the auto-chain launcher (waits on the download). Non-fatal."""
    cfg = cluster_cfg or {}
    secrets = secrets or {}
    host = (cfg.get("ssh_host") or "").strip()
    user = (cfg.get("ssh_user") or "").strip()
    port = str(cfg.get("ssh_port") or "22").strip() or "22"
    keyfile = (cfg.get("ssh_key") or "").strip()
    password = secrets.get("ssh_password") or ""
    dl_tag = (cfg.get("JOB_TAG") or "sra").strip() or "sra"
    star_tag = f"{dl_tag}_star"
    star_root = f"{download_root.rstrip('/')}/star"

    if not host or not user:
        print("  STAR SUBMIT: missing SSH host/user -> bundle still downloadable")
        return {"submitted": False, "reason": "missing host/user",
                "diagnosis": cluster_deploy.diagnose_failure("missing host/user")}
    if not os.path.isdir(P.star_dir):
        return {"submitted": False, "reason": "no bundle",
                "diagnosis": cluster_deploy.diagnose_failure("", "no bundle")}

    # Launch on the cluster: wait for the download watchdog (if found), then run the sentinel launcher.
    launch = (
        f"WID=$(bjobs -noheader -o jobid -J '{dl_tag}_watchdog' 2>/dev/null | head -1); "
        f'DEP=""; [ -n "$WID" ] && DEP="-w ended($WID)"; '
        f"bsub -L /bin/bash -n 1 -M 2000 -W 30 -J '{star_tag}_launch' $DEP "
        f"-o '{star_root}/launch.out' -e '{star_root}/launch.err' '{star_root}/star_launch.sh'"
    )
    print(f"=== STAR SUBMIT: {user}@{host}:{port} -> {star_root} ===")
    try:
        if password:
            try:
                import paramiko  # noqa: F401
            except Exception:
                raise RuntimeError("password auth needs paramiko (pip install paramiko) or use an SSH key")
            res = cluster_deploy._submit_paramiko(P, host, port, user, password, keyfile, star_root,
                                                  reporter, src_dir=P.star_dir, launch_cmd=launch)
        else:
            res = cluster_deploy._submit_systemssh(P, host, port, user, keyfile, star_root,
                                                   reporter, src_dir=P.star_dir, launch_cmd=launch)
        print(f"  STAR SUBMIT: auto-chain launcher queued on {host} (waits for the download to finish)")
        return res
    except Exception as e:
        output = getattr(e, "output", "") or str(e)
        diag = cluster_deploy.diagnose_failure(output, str(e))
        print(f"  STAR SUBMIT FAILED: {e}  -> {diag['title']}")
        print("  -> the STAR bundle is still downloadable (RUN_STAR_ON_CLUSTER.txt).")
        reporter.set_detail(f"STAR submit failed: {diag['title']}")
        return {"submitted": False, "reason": str(e), "diagnosis": diag}
